### ISSUE TITLE
甚至十天后都没有人回复 Model converted from tflite giving empty output tensor

### ISSUE THREAD

**Issue by kafan1986** [alibaba/MNN#800]
# Platform(Include target platform as well if cross-compiling):  
Android

# Github Version:
Latest Release version V1.0.0

# Compiling Method

# Build Log:

The problem is I converted a model from tflite and it worked OK on tensorflow lite. Now after conversion. The inference output of mnn model is empty. I have printed output tensor's shape and it is giving me (0,0,0,0). Whereas it should give me 1x7 values as per original tflite model.

The mnn model file is attached.

The code used to run the model is below:

```
int Eliotface::GetEmotion(const cv::Mat& img_face, std::vector<float>* feat) {
    feat->clear();
    if (!initialized_) {
        __android_log_print(ANDROID_LOG_ERROR, APPNAME, "Eliotface emotion model uninitialized");
        return 10000;
    }
    if (img_face.empty()) {
        __android_log_print(ANDROID_LOG_ERROR, APPNAME, "Eliotface face mat empty");
        return 10001;
    }

    if (img_face.channels() != 1) {
        __android_log_print(ANDROID_LOG_ERROR, APPNAME, "Eliotface face needs to be grayscale");
        return 10002;
    }

    cv::Mat img_resized;
    cv::resize(img_face, img_resized, inputSize_, 0, 0, CV_INTER_CUBIC);

    img_resized.convertTo(img_resized, CV_32FC1, 1.0f/127.0f, -1.0f);

    auto nhwc_tensor = MNN::Tensor::create<float>({ 1,inputSize_.height, inputSize_.width, 1}, NULL, MNN::Tensor::TENSORFLOW);
    auto nhwc_data   = nhwc_tensor->host<float>();
    auto nhwc_size   = nhwc_tensor->size();
    ::memcpy(nhwc_data, img_resized.data, nhwc_size);
    input_tensor_emotion->copyFromHostTensor(nhwc_tensor);

    eliotnet_interpreter_emotion_->runSession(eliotnet_sess_emotion_);

    // get output
    std::string output_name = "Identity";

    auto output_feat = eliotnet_interpreter_emotion_->getSessionOutput(eliotnet_sess_emotion_,output_name.c_str());

    // get output
    MNN::Tensor feat_tensor(output_feat, output_feat->getDimensionType());
    output_feat->copyToHostTensor(&feat_tensor);
    __android_log_print(ANDROID_LOG_VERBOSE, APPNAME, "DEBUG Size %d %d %d %d",output_feat->shape()[0], output_feat->shape()[1], output_feat->shape()[2], output_feat->shape()[3]);

    feat->resize(7); // Index 0 to 7 (Total 7 values represent the 7 emotion exactly in order as expected
    for(int i = 0; i < 7; i++){
        feat->at(i) = feat_tensor.host<float>()[i];
    }
    return 0;
}

```
[et.mnn.zip](https://github.com/alibaba/MNN/files/4631285/et.mnn.zip)

[et.tflite.zip](https://github.com/alibaba/MNN/files/4638721/et.tflite.zip)

**Comment by kafan1986** [comment]
@jxt1234
Any help?

**Comment by jxt1234** [comment]
模型转换时会打印输入输出的名字，你这个最后一层是 Identity 会被去掉，需要取上一层的名字

**Comment by kafan1986** [comment]
@jxt1234 
```

MNNConverter Version: 0.2.1.5git - MNN @ 2018


Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
[13:10:43] :20: Inputs: input_1
[13:10:43] :37: Outputs: Identity, Type = Softmax
Converted Done!
```

What to use as output layer's name then?

**Comment by jxt1234** [comment]
1.模型转换这个名字貌似是bug，你如果是单输出的话取 net->getSessionOutput(nullptr) 就好了
2. 是否你的输入没有初始大小

**Comment by kafan1986** [comment]
> 1. The name of the model conversion seems to be a bug, if you are single output, just take net->getSessionOutput(nullptr).
> 2. Whether your input has no initial size

@jxt1234 
```
1.     auto output_feat = eliotnet_interpreter_emotion_->getSessionOutput(eliotnet_sess_emotion_,
                                                                       nullptr);
```

still gives empty output tensor

2. Input has (1x48x48x3) size in nhwc format

**Comment by jxt1234** [comment]
It's because of the matmul in tflite has broadcast. Has been solved now. Please update the code

**Comment by kafan1986** [comment]
@jxt1234 I have downloaded and compiled the MNN converter on my mac and reconverted the model from TFLITE to MNN but even with the new .mnn model file the error remains. Do I need to update the ARM libraries on my Android? I don't have proper setup to build the armv7 and v8 libraries. If this as well needs to be updated too then can you share the latest version here?

**Comment by jxt1234** [comment]
The ARM libraries should be re-compiled. You can refer 
https://www.yuque.com/mnn/cn/build_android
or 
https://www.yuque.com/mnn/en/build_android
to build ARM libraries.

**Comment by kafan1986** [comment]
@jxt1234 I have built the android libraries and model converter tool. I then reconverted the tflite model to mnn via latest model converter tool. I built 2 version fp16 and fp32 version. 

A) When I use fp32 version model. Immediate crash during initialization of model.

B) When I use fp16 version model. It runs and output size is correct - 1 x 1 x 7 x 1 but all the final values are shown as 1.0 which is incorrect.

I have attached latest converted models.

```
__android_log_print(ANDROID_LOG_ERROR, APPNAME, "DEBUG 1 nhwc_size %d",nhwc_size);

    // get output
    auto output_feat = eliotnet_interpreter_emotion_->getSessionOutput(eliotnet_sess_emotion_,
                                                                       nullptr);

    // get output
    MNN::Tensor feat_tensor(output_feat, output_feat->getDimensionType());
    output_feat->copyToHostTensor(&feat_tensor);
    __android_log_print(ANDROID_LOG_ERROR, APPNAME, "DEBUG 2 dimentype %d %d %d %d",feat_tensor.width(),feat_tensor.height(),feat_tensor.channel(),feat_tensor.batch());

    feat->resize(7); // Index 0 to 7 (Total 7 values represent the 7 emotion exactly in order as expected
    for(int i = 0; i < 7; i++){
        __android_log_print(ANDROID_LOG_ERROR, APPNAME, "DEBUG 3 %d %f",i,feat_tensor.host<float>()[i]);
        feat->at(i) = feat_tensor.host<float>()[i];
    }
```

**Output**

```
DEBUG 1 nhwc_size 9216
2020-06-04 15:24:28.040 2950-3277/E/EliotFace v1.1: DEBUG 2 dimentype 1 1 7 1
2020-06-04 15:24:28.040 2950-3277/E/EliotFace v1.1: DEBUG 3 0 1.000000
2020-06-04 15:24:28.040 2950-3277/E/EliotFace v1.1: DEBUG 3 1 1.000000
2020-06-04 15:24:28.040 2950-3277/E/EliotFace v1.1: DEBUG 3 2 1.000000
2020-06-04 15:24:28.040 2950-3277/E/EliotFace v1.1: DEBUG 3 3 1.000000
2020-06-04 15:24:28.040 2950-3277/E/EliotFace v1.1: DEBUG 3 4 1.000000
2020-06-04 15:24:28.040 2950-3277/E/EliotFace v1.1: DEBUG 3 5 1.000000
2020-06-04 15:24:28.040 2950-3277/E/EliotFace v1.1: DEBUG  3 6 1.000000
```

[Latest fp16  fp32 models.zip](https://github.com/alibaba/MNN/files/4729220/Latest.fp16.fp32.models.zip)

**Comment by jxt1234** [comment]
how do you set the input and run mnn ?

**Comment by kafan1986** [comment]
> how do you set the input and run mnn ?

@jxt1234 

```
    cv::Mat img_resized;
    cv::resize(img_face, img_resized, inputSize_, 0, 0, CV_INTER_CUBIC);

    img_resized.convertTo(img_resized, CV_32FC1, 1.0f/127.0f, -1.0f);

    // MNN ImageProcess不支持dstformat为MNN_DATA_FORMAT_NCHW
    // 需要自己定义TENSORFLOW或CAFFE_C4格式tensor进行赋值
    auto nhwc_tensor = MNN::Tensor::create<float>({ 1,inputSize_.height, inputSize_.width, 1}, NULL, MNN::Tensor::TENSORFLOW);
    auto nhwc_data   = nhwc_tensor->host<float>();
    auto nhwc_size   = nhwc_tensor->size();
    ::memcpy(nhwc_data, img_resized.data, nhwc_size);

    input_tensor_emotion->copyFromHostTensor(nhwc_tensor);

    __android_log_print(ANDROID_LOG_ERROR, APPNAME, "DEBUG 0 nhwc_size ");
    eliotnet_interpreter_emotion_->runSession(eliotnet_sess_emotion_);
```

Complete cpp and header files are attached.

[Code.zip](https://github.com/alibaba/MNN/files/4730961/Code.zip)

**Comment by kafan1986** [comment]
@jxt1234 Apart from the above issue. I am noticing that it is giving me crashes at this line sometimes.

`eliotnet_interpreter_emotion_->runSession(eliotnet_sess_emotion_);`

**Crash logs:**

```
2020-06-04 21:33:21.356 29771-29771/? A/DEBUG: pid: 29512, tid: 29644, name: AsyncTask #1  >>>  <<<
2020-06-04 21:33:21.356 29771-29771/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7cd7000000
2020-06-04 21:33:21.357 29771-29771/? A/DEBUG:     x0  0000007cd6fea440  x1  0000007cd7000000  x2  0000007cd69f1110  x3  0000000000000010
2020-06-04 21:33:21.357 29771-29771/? A/DEBUG:     x4  0000000000000020  x5  0000000000000003  x6  0000000000000003  x7  0000000000000010
2020-06-04 21:33:21.357 29771-29771/? A/DEBUG:     x8  00000000000002e0  x9  0000000000000001  x10 0000000000000000  x11 0000000000000180
2020-06-04 21:33:21.357 29771-29771/? A/DEBUG:     x12 0000000000000100  x13 0000007cd6fff8e0  x14 0000007cd69f1080  x15 000000000000000d
2020-06-04 21:33:21.357 29771-29771/? A/DEBUG:     x16 0000000000000002  x17 0000000000000000  x18 0000000000000001  x19 0000007cd6d56240
2020-06-04 21:33:21.357 29771-29771/? A/DEBUG:     x20 0000007cd6d5626c  x21 0000007d106afd00  x22 0000007cd6fe9340  x23 0000007cd69f1080
2020-06-04 21:33:21.357 29771-29771/? A/DEBUG:     x24 0000007cd6ffb480  x25 0000000000000004  x26 0000007cd6fd5c40  x27 0000007cd6fe0340
2020-06-04 21:33:21.357 29771-29771/? A/DEBUG:     x28 0000007cebe7e090  x29 0000007cebe7e2f0
2020-06-04 21:33:21.357 29771-29771/? A/DEBUG:     sp  0000007cebe7dfa0  lr  0000007ce0f0084c  pc  0000007ce0f44164
2020-06-04 21:33:21.436 29771-29771/? A/DEBUG: backtrace:
2020-06-04 21:33:21.436 29771-29771/? A/DEBUG:     #00 pc 00000000000ed164  /data/app/--yb3LJoZbKI8wgiMIA1F1Q==/lib/arm64/libMNN.so
2020-06-04 21:33:21.436 29771-29771/? A/DEBUG:     #01 pc 00000000000a9848  /data/app/--yb3LJoZbKI8wgiMIA1F1Q==/lib/arm64/libMNN.so
2020-06-04 21:33:21.436 29771-29771/? A/DEBUG:     #02 pc 00000000000a9bec  /data/app/--yb3LJoZbKI8wgiMIA1F1Q==/lib/arm64/libMNN.so
2020-06-04 21:33:21.436 29771-29771/? A/DEBUG:     #03 pc 00000000000eb650  /data/app/--yb3LJoZbKI8wgiMIA1F1Q==/lib/arm64/libMNN.so (MNN::ThreadPool::enqueue(std::__ndk1::pair<std::__ndk1::function<void (int)>, int>&&, int)+140)
2020-06-04 21:33:21.437 29771-29771/? A/DEBUG:     #04 pc 00000000000a89e8  /data/app/--yb3LJoZbKI8wgiMIA1F1Q==/lib/arm64/libMNN.so
2020-06-04 21:33:21.437 29771-29771/? A/DEBUG:     #05 pc 0000000000046208  /data/app/--yb3LJoZbKI8wgiMIA1F1Q==/lib/arm64/libMNN.so
2020-06-04 21:33:21.437 29771-29771/? A/DEBUG:     #06 pc 000000000004f948  /data/app/--yb3LJoZbKI8wgiMIA1F1Q==/lib/arm64/libMNN.so (MNN::Session::run() const+52)
```

**Comment by kafan1986** [comment]
@jxt1234 

I rebuild the android libraries with **Debug** flag and analyzed the crash

**Crash Logs:**
```
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG: pid: 7119, tid: 7236, name: AsyncTask #1  >>> com.ss.peoplecounting <<<
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7cde000010
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG:     x0  0000007cddfd37c0  x1  0000007cde000010  x2  0000007cdfbfd2a0  x3  0000000000000010
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG:     x4  0000000000000020  x5  0000000000000003  x6  0000000000000003  x7  0000000000000010
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG:     x8  00000000000002e0  x9  0000000000000001  x10 0000000000000002  x11 0000000000000180
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG:     x12 0000000000000100  x13 0000007cddfff9b0  x14 0000007cdfbfd230  x15 0000000000000008
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG:     x16 0000007ce30f6ae0  x17 0000007ce0ac9450  x18 0000000000000001  x19 0000007ce30f7300
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG:     x20 0000007d18db31f0  x21 0000000000002400  x22 0000007d12427920  x23 0000007d125ec040
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG:     x24 0000007ce30f9588  x25 0000007ce30f7288  x26 0000007ce07d90a0  x27 0000000000000004
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG:     x28 0000007ce30f73b0  x29 0000007ce30f6b60
2020-06-04 23:04:56.228 7267-7267/? A/DEBUG:     sp  0000007ce30f6ae0  lr  0000007ce0be2a18  pc  0000007ce0d20dfc
/? A/DEBUG: backtrace:
/? A/DEBUG:     #00 pc 000000000040fdfc  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #01 pc 00000000002d1a14  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #02 pc 00000000002d16f0  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #03 pc 00000000002d1658  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #04 pc 00000000002d15dc  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #05 pc 00000000002d0420  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #06 pc 00000000002d3e34  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #07 pc 00000000002d3d78  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so (std::__ndk1::function<void (float const*, float*, int)>::operator()(float const*, float*, int) const+120)
/? A/DEBUG:     #08 pc 00000000002d3cf0  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #09 pc 00000000002d3c94  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #10 pc 00000000002d3c2c  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #11 pc 00000000002d3be0  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #12 pc 00000000002d28f0  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #13 pc 0000000000244678  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so
/? A/DEBUG:     #14 pc 00000000002445ec  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so (std::__ndk1::function<void (int)>::operator()(int) const+72)
/? A/DEBUG:     #15 pc 000000000040502c  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so (MNN::ThreadPool::enqueue(std::__ndk1::pair<std::__ndk1::function<void (int)>, int>&&, int)+100)
/? A/DEBUG:     #16 pc 00000000002ce2f4  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so (MNN::CPUConvolutionDepthwise::BasicFloatExecution::onExecute(std::__ndk1::vector<MNN::Tensor*, std::__ndk1::allocator<MNN::Tensor*>> const&, std::__ndk1::vector<MNN::Tensor*, std::__ndk1::allocator<MNN::Tensor*>> const&)+380)
/? A/DEBUG:     #17 pc 00000000002cf600  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so (MNN::CPUConvolutionDepthwise::FloatExecution::onExecute(std::__ndk1::vector<MNN::Tensor*, std::__ndk1::allocator<MNN::Tensor*>> const&, std::__ndk1::vector<MNN::Tensor*, std::__ndk1::allocator<MNN::Tensor*>> const&)+68)
/? A/DEBUG:     #18 pc 00000000002cc94c  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so (MNN::CPUConvolutionDepthwise::onExecute(std::__ndk1::vector<MNN::Tensor*, std::__ndk1::allocator<MNN::Tensor*>> const&, std::__ndk1::vector<MNN::Tensor*, std::__ndk1::allocator<MNN::Tensor*>> const&)+56)
 7267-7267/? A/DEBUG:     #19 pc 000000000017ef64  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so (MNN::Pipeline::Unit::execute()+132)
 7267-7267/? A/DEBUG:     #20 pc 000000000018057c  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so (MNN::Pipeline::execute()+120)
 7267-7267/? A/DEBUG:     #21 pc 00000000001b709c  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so (MNN::Session::run() const+156)
 7267-7267/? A/DEBUG:     #22 pc 000000000015b7f0  /data/app/com.ss.peoplecounting-GLr6-ITCglfkEZsFp_SMMg==/lib/arm64/libMNN.so (MNN::Interpreter::runSession(MNN::Session*) const+24)
```

**addr2line output:**

`/Users/testuser/android_sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-addr2line -e /path/to/libMNN.so -C -f 000000000040fdfc`

**Addr2line Output:**
L8LoopW
/home/ubuntu/MNN/source/backend/cpu/arm/arm64/MNNConvRunForLineDepthwise.S:77

**Comment by kafan1986** [comment]
@jxt1234 Did you find the time to look into the above two issues:
1) Output tensor values are all 1.0s
2) Intermittent crash at **runSession**

**Comment by kafan1986** [comment]
@jxt1234 The cpp file are attached. The final output is still all 1.0s.

[eliotnet.zip](https://github.com/alibaba/MNN/files/4801480/eliotnet.zip)

**Comment by andreydung** [comment]
I met the same problem. It seems that if the model is too large, then runSession met error and thus output Tensor would be null (all shapes are zero).

**Comment by kafan1986** [comment]
> I met the same problem. It seems that if the model is too large, then runSession met error and thus output Tensor would be null (all shapes are zero).

What do you mean by model size too big? The model where the issue occured, was around 12 MB in size. Whereas I have worked with 100+ MB model on same hardware and config. Actually there is some bug in MNN. Earlier there was no output layer detected by the MNN. Once I raised the issue. They made certain changes and the output layer shape was correctly detected but the output was all 1s and there was intermittent crashes.

**Comment by DavorJordacevic** [comment]
> > I met the same problem. It seems that if the model is too large, then runSession met error and thus output Tensor would be null (all shapes are zero).
> 
> What do you mean by model size too big? The model where the issue occured, was around 12 MB in size. Whereas I have worked with 100+ MB model on same hardware and config. Actually there is some bug in MNN. Earlier there was no output layer detected by the MNN. Once I raised the issue. They made certain changes and the output layer shape was correctly detected but the output was all 1s and there was intermittent crashes.
`
Is there a way to overcome this? My model is around 250MB, and I am getting this output when loading the model.
I/scudo: Stats: SizeClassAllocator64: 286M mapped (0M rss) in 2874735 allocations; remains 109082
      00 (   128): mapped:    256K popped:  205576 pushed:  203798 inuse:   1778 total:   1904 rss:      0K releases:      0 last released:      0K region: 0x7080394000 (0x7080388000)
      01 (    32): mapped:    256K popped:    8862 pushed:    2982 inuse:   5880 total:   6552 rss:      0K releases:      0 last released:      0K region: 0x7090389000 (0x7090388000)
 ........
      37 (229392): mapped:   1280K popped:      12 pushed:       8 inuse:      4 total:      5 rss:      0K releases:      3 last released:    448K region: 0x72d0397000 (0x72d0388000)
      38 (262160): mapped:    768K popped:       2 pushed:       0 inuse:      2 total:      2 rss:      0K releases:      0 last released:      0K region: 0x72e038c000 (0x72e0388000)
    Scudo OOM: The process has Exhausted 256M for size class 4624.
`
   
And this output when trying to get output from a specific layer. However, with smaller models, my code works as excpeted.
`
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 2736 (verification), pid 2736 (verification)
`

Also, without specifying the layer name, my code will return some output, but the same for different inputs.
